name: deepl-segment-bio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy<=2.2
  - numba
  - scipy
  - pandas
  - scikit-image
  - scikit-learn
  - matplotlib
  - seaborn
  - anndata
  - spatialdata
  - spatialdata-io
  - spatialdata-plot
  - cellpose
  - squidpy
  - statsmodels
  - xarray
  - dask
  - ipython
  - jupyterlab
  - pip
  # ... all other packages from your conda list ...
  - pip:
      # Pip-only packages from your original list, but
      # EXCLUDING: numpy, numba, scipy, pandas, scikit-learn, scikit-image, matplotlib, seaborn
      # (these should be installed ONLY via conda)
      - absl-py==2.3.1
      - aiobotocore==2.23.1
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - app-model==0.3.2
      - appdirs==1.4.4
      - astunparse==1.6.3
      - babel==2.17.0
      - bin2cell==0.3.3
      - botocore==1.38.46
      - build==1.2.2.post1
      - cachey==0.2.1
      - comm==0.2.2
      - cramjam==2.10.0
      - csbdeep==0.8.1
      - debugpy==1.8.15
      - docstring-parser==0.17.0
      - docutils==0.21.2
      - fastparquet==2024.11.0
      - flexcache==0.3
      - flexparser==0.4
      - flowio==1.4.0
      - freetype-py==2.5.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - heapdict==1.0.1
      - hsluv==5.0.4
      - igraph==0.11.9
      - imagesize==1.4.1
      - in-n-out==0.2.1
      - ipykernel==6.30.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - keras==3.10.0
      - libclang==18.1.1
      - loguru==0.7.3
      - magicgui==0.10.1
      - markdown==3.8.2
      - ml-dtypes==0.5.1
      - namex==0.1.0
      - napari==0.5.5
      - napari-console==0.1.3
      - napari-matplotlib==3.0.0
      - napari-plugin-engine==0.2.0
      - napari-spatialdata==0.5.6
      - napari-svg==0.2.1
      - npe2==0.7.9
      - numpydoc==1.9.0
      - ome-types==0.6.1
      - opt-einsum==3.4.0
      - pint==0.24.4
      - psygnal==0.14.0
      - pydantic==2.11.7
      - pydantic-compat==0.1.2
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pyopengl==3.1.9
      - pyproject-hooks==1.2.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
      - pyzmq==27.0.0
      - qtconsole==5.6.1
      - readfcs==2.0.1
      - referencing==0.36.2
      - roman-numerals-py==3.1.0
      - rpds-py==0.26.0
      - scanpy==1.11.3
      - shellingham==1.5.4
      - snowballstemmer==3.0.1
      - sopa==2.1.1
      - stardist==0.9.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - texttable==1.7.0
      - tifffile==2025.5.10
      - tiffslide==2.5.1
      - tinycss2==1.4.0
      - tomli-w==1.2.0
      - typer==0.16.0
      - typing-inspection==0.4.1
      - vispy==0.14.3
      - werkzeug==3.1.3
      - xarray-datatree==0.0.14
      - xsdata==24.3.1