---
title: "Plot of a subset of genes, interesting for the biologist"
output: html_document
params:
  saves_path_stem: "my_segmentation/filtered/interesting_genes"
  labels_key: "labels_singler"
  spe_key: "pseudobulk_celltype_SingleR_wb7_wdiscard"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(purrr)
library(dplyr)
library(tidyr)
library(Banksy)
library(DropletUtils)
library(ggplot2)
library(ggspavis)
library(patchwork)
library(scDblFinder)
library(SingleCellExperiment)
library(SpatialExperiment)
library(scuttle)
library(edgeR)
library(spacexr)
library(SpotSweeper)
library(sva)
source("/mnt/europa/valerio/repositories/cachetic_visiumHD/r_scripts/utils/utils_fun.R")
```

Paths
```{r}
pl_path = paste0("/mnt/europa/valerio/repositories/cachetic_visiumHD/figures/output_R/SingleR_annot/", params$saves_path_stem,"/")
Rd_path = "/mnt/europa/valerio/data/Rdata/"
ref_path = "/mnt/europa/valerio/data/multiome_sce/multiome_sce.rds"
res_path = paste0("/mnt/europa/valerio/repositories/cachetic_visiumHD/results/SingleR_annot/", params$saves_path_stem, "/")
```

```{r}
pb_ct <- readRDS(paste0(Rd_path, params$spe_key))
markers <- read.table("/mnt/europa/valerio/repositories/cachetic_visiumHD/json/identity_genes.txt", header = FALSE)[[1]] |> as.character()
```

```{r}
df <- as.data.frame(t(logcounts(pb_ct)[markers, , drop=FALSE])) 
df$sample    <- colData(pb_ct)$sample_id
df$condition <- colData(pb_ct)$tissue_type
df$celltype  <- colData(pb_ct)[[params$labels_key]]

df_long <- pivot_longer(df, cols = all_of(markers),
                        names_to = "gene", values_to = "expr")

df <- df |>
  filter(condition %in% c("sham","c26"))

df_long <- pivot_longer(df, cols = all_of(markers),
                        names_to = "gene", values_to = "expr")

# calcolo media e percentuale per ogni celltype × condition × gene
dot_data <- df_long %>%
  group_by(condition, celltype, gene) %>%
  summarise(
    pct_expr = sum(expr > 0) / n() * 100,
    avg_expr = mean(expr[expr > 0], na.rm = TRUE),
    .groups = "drop"
  )
```


```{r}
# genera grafici separati per ogni marker
plots <- imap(markers, function(marker, name){
  dot_plot_marker(dot_data, gene_to_plot = marker)
})
names(plots) <- markers

iwalk(plots, function(plot, name){
  ggsave(paste0(pl_path,"dot_plots_sham&c26_only/", name, ".png"), 
         plot = plot, dpi = 400, units = "cm", width = 50, height = 30, create.dir = TRUE)
})
```

