---
title: "Annotazione del campione segmentato con ariosi"
author: "Valerio Reffo"
date: "2026-02-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=FALSE, warning=FALSE, include=FALSE}
library(purrr)
library(ggplot2)
library(ggspavis)
library(jsonlite)
library(anndataR)
library(scuttle)
library(SpatialExperiment)
library(data.table)
# to read spatialdata objects
library(ggnewscale)
#library(SpatialData)
library(SingleCellExperiment)
library(SingleR)
library(BiocParallel)
source("/mnt/europa/valerio/repositories/cachetic_visiumHD/r_scripts/utils/utils_fun.R")
```

Define the paths
```{r}
pl_path = paste0("/mnt/europa/valerio/repositories/cachetic_visiumHD/figures/output_R/SingleR_arivis/")
Rd_path = "/mnt/europa/valerio/data/Rdata/"
ref_path = "/mnt/europa/valerio/data/multiome_sce/multiome_sce.rds"
# res_path = paste0("/mnt/europa/valerio/repositories/cachetic_visiumHD/results/SingleR_markers_annot/", params$saves_path_stem, "/")
```

```{r}
sce <- read_h5ad('/mnt/europa/valerio/data/zarr_store/adatas/arivis_segmentation_tables/blocco1_sham.h5ad', as = "SingleCellExperiment")

assayNames(sce) <- "counts"
sce <- scuttle::logNormCounts(sce)
sce

saveRDS(sce, file = "/mnt/europa/valerio/data/Rdata/sce_arivis_nuclei.rds")
```

```{r}
color_vector <- readRDS(paste0(Rd_path, "color_cell_dec"))

sce_ref <- readRDS(ref_path)
marker_genes <- readRDS(paste0(Rd_path, "marker_genes_list_singleR_annot"))
load(paste0(Rd_path, "markers_list_mixed.RData")) # name markers

```

Marker short list
```{r}
pred.mark <- SingleR(test = sce, ref = sce_ref, labels = sce_ref$subclusters, genes = marker_genes, BPPARAM = MulticoreParam(8))
```

Marker long list
```{r}
pred.mark_long <- SingleR(test = sce, ref = sce_ref, labels = sce_ref$subclusters, genes = markers, BPPARAM = MulticoreParam(10))
```

Wilcoxon method
```{r}
pred.ann <- SingleR(test = sce, ref = sce_ref, de.method = "wilcox", labels = sce_ref$subclusters, BPPARAM=MulticoreParam(10))
```

```{r}
base::table(pred.mark$pruned.labels)
base::table(pred.mark_long$pruned.labels)
base::table(pred.ann$pruned.labels)
```

```{r}
colData(sce)
sce$singleR_marker_annot <- pred.mark$pruned.labels
sce$singleR_annot <- pred.ann$pruned.labels
sce$singleR_marker_long_annot <- pred.mark_long$pruned.labels
```

# Plots

```{r}
plot_data <- as.data.frame(colData(sce))
```


```{r}
toplot <- c("singleR_marker_annot", "singleR_annot", "singleR_marker_long_annot")
# 2. Plot
plotti <- map(toplot, \(col) {
  ggplot(plot_data, aes(x = x_coord, y = y_coord, color = .data[[col]])) +
    geom_point(size = 0.5) + 
    coord_fixed() +
    scale_color_manual(values = color_vector) + # Uncomment if you have your vector
    scale_y_reverse() +
    theme_minimal() + # Good starting theme
    theme(
      legend.key.width  = unit(0.5, "lines"),
      legend.key.height = unit(1, "lines"),
      axis.title = element_blank(),
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      panel.grid = element_blank() # Usually desired for spatial plots
    ) +
    guides(color = guide_legend(override.aes = list(size = 5)))
})
names(plotti) <- toplot
iwalk(plotti, function(plot, name){
  ggsave(paste0(pl_path, name, ".png"), plot = plot, dpi = 400, units = "cm", width = 50, height = 30, create.dir = TRUE)
})
```

single plot
```{r}
colData(sce) |> as_tibble() |> 
  ggplot(aes(x = x_coord, y = y_coord)) +
    geom_point(size = 0.8, color = "lightblue") + 
    coord_fixed() +
    scale_color_manual(values = color_vector) + # Uncomment if you have your vector
    scale_y_reverse() +
    theme_minimal() + # Good starting theme
    theme(
      legend.key.width  = unit(0.5, "lines"),
      legend.key.height = unit(1, "lines"),
      axis.title = element_blank(),
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      panel.grid = element_blank() # Usually desired for spatial plots
    ) +
    guides(color = guide_legend(override.aes = list(size = 5)))
```


# Barplot

```{r}
# 1. Define the columns to plot
cols_to_plot <- c("singleR_marker_annot", "singleR_annot", "singleR_marker_long_annot")

# 2. Calculate proportions for each column and combine
prop_df <- map_dfr(cols_to_plot, function(col_name) {
  
  # Get the vector of labels
  labels <- colData(sce)[[col_name]]
  
  # Create a table of counts and convert to proportions
  prop_table <- prop.table(base::table(labels, useNA = "ifany"))
  
  # Return a tidy dataframe
  tibble(
    method = col_name,
    cell_type = names(prop_table),
    proportion = as.numeric(prop_table)
  )
}) 

# 3. Plot
p2 <- ggplot(prop_df, aes(x = method, y = proportion, fill = cell_type)) +
  geom_col(width = 0.7) + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_fill_manual(values = color_vector) + 
  labs(
    title = "Cell Type Proportions by Annotation Method",
    x = "Annotation Method", 
    y = "Proportion", 
    fill = "Cell Type"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid.major.x = element_blank()
  )

ggsave(paste0(pl_path, "cell_type_prop.png"), plot = p2, dpi = 700, create.dir = TRUE)
```


# Markers identified by SingleR

```{r}
dim(pred.ann$scores)
attr(pred.ann)
```


Myonuclei alone
```{r}
mionuclei <- c("Myonuclei_IIb", "Myonuclei_IIx", "Myonuclei_IIx_IIb", "Myonuclei_MTJ", "Myonuclei_IIx_IIa", "Myonuclei_NMJ", "Myonuclei_Trim63")

plotMarkerHeatmap(pred.ann, sce, label = "Myonuclei_IIx_IIb",
                  other.labels = mionuclei, top = 20, num.threads = 4)
```

