---
title: "DGE_singleR"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(purrr)
library(dplyr)
library(tidyr)
library(DropletUtils)
library(SingleCellExperiment)
library(SpatialExperiment)
library(scuttle)
library(edgeR)
library(openxlsx)
source("/mnt/europa/valerio/repositories/cachetic_visiumHD/r_scripts/utils/utils_fun.R")
```


Paths
```{r}
pl_path = "/mnt/europa/valerio/repositories/cachetic_visiumHD/figures/output_R/singler_annot/"
Rd_path = "/mnt/europa/valerio/data/Rdata/"
ref_path = "/mnt/europa/valerio/data/multiome_sce/multiome_sce.rds"
res_path = "/mnt/europa/valerio/repositories/cachetic_visiumHD/results/DGE_singleR/"
```

Loading pseudobulk with cell_types and single-cell reference and others
```{r}
load(paste0(Rd_path, "pseudobulk_celltype_SingleR.RData"))

load(paste0(Rd_path, "color_cell_dec.RData"))
load(paste0(Rd_path, "contrast_list.RData"))
```

```{r}
pb_ct
colData(pb_ct)
pb_ct$cell_type <- pb_ct$labels_singler
pb_ct_wb7$cell_type <- pb_ct_wb7$labels_singler
```


# DEGs FOR ALL SAMPLE TYPES

```{r}
deg_fun_emma <- \(pseudobulk_exp, contrast_list)
{
  lrt_list <- list()
  summary_list <- list()
 
  for (contrast_name in names(contrast_list)) {
    lrt_list[[contrast_name]] <- list()
    
    for (cell_type in unique(pseudobulk_exp$cell_type)) {
      ct_pb <- pseudobulk_exp[, pseudobulk_exp$cell_type == cell_type]
      y <- edgeR::DGEList(assay(ct_pb), samples = as.data.frame(colData(ct_pb)))
      keep <- edgeR::filterByExpr(y, group = y$samples$tissue_type)
      y <- y[keep,, keep.lib.sizes=FALSE]
      y <- edgeR::calcNormFactors(y) 
      design <- model.matrix(~ 0 + tissue_type, y$samples)
      y <- estimateDisp(y, design)
      fit <- glmFit(y, design)
      
      contrast <- makeContrasts(contrasts = contrast_list[[contrast_name]], levels = design)
      
      lrt <- glmLRT(fit, contrast = contrast)
      res <- topTags(lrt, n = Inf)$table
      res$significant <- res$FDR < 0.05
      
      sig <- res[res$significant, ]
      sig_up <- sig[sig$logFC >= 0, ]
      sig_down <- sig[sig$logFC < 0, ]
      
      lrt_list[[contrast_name]][[cell_type]] <- list(
        full = res,
        sig = sig,
        up = sig_up,
        down = sig_down
      )
      
      gene_summary <- data.frame(
        contrast = contrast_name,
        cell_type = cell_type,
        Geni_considerati = nrow(res),
        Geni_significativi = nrow(sig),
        Upregolati = nrow(sig_up),
        Downregolati = nrow(sig_down)
      )
      
      summary_list[[length(summary_list) + 1]] <- gene_summary
    }
  }
  return(list(summary = summary_list, lrt = lrt_list))
}
```


```{r}
# Tabella riassuntiva

degged <- deg_fun_emma(pb_ct_wb7, contrast_list)

save(degged, file = paste0(Rd_path, "deg_results_list_wb7.RData"))

summary_df <- do.call(rbind, degged$summary)
print(summary_df)
```

Summary summmary table
```{r}
final_summary_table <- summary_df |> 
  # Group the data by the 'contrast' column
  group_by(contrast) |> 
  # Calculate the sum of up- and down-regulated genes for each group
  summarise(
    N_up_DEG = sum(Upregolati, na.rm = TRUE),
    N_down_DEG = sum(Downregolati, na.rm = TRUE)
  ) |> 
  # Calculate the total number of differentially expressed genes (DEG)
  mutate(
    N_DEG = N_up_DEG + N_down_DEG
  ) |> 
  # Rename the 'contrast' column to 'Confronti' to match the desired output
  rename(
    Confronti = contrast
  )

# Print the final table
print(final_summary_table)
```


## Summary results

```{r}

wb <- createWorkbook()

# Aggiungo uno sheet per ogni contrasto con la tabella completa
for (contrast_name in unique(summary_df$contrast)) {
  contrast_table <- subset(summary_df, contrast == contrast_name)
  
  addWorksheet(wb, contrast_name)
  writeData(wb, contrast_name, contrast_table)
}

saveWorkbook(wb = wb, file = paste0(res_path, "summary_contrasts.xlsx"), overwrite = TRUE)
```

## All results

For each contrast pvalues of every gene

```{r}
lrt_list <- degged$lrt

for (contrast_name in names(lrt_list)) {
  wb <- createWorkbook()
  
  for (cell_type in names(lrt_list[[contrast_name]])) {
    res     <- lrt_list[[contrast_name]][[cell_type]]$full
    sig     <- lrt_list[[contrast_name]][[cell_type]]$sig
    sig_up  <- lrt_list[[contrast_name]][[cell_type]]$up
    sig_down<- lrt_list[[contrast_name]][[cell_type]]$down
    
    # nome foglio pulito
    clean_name <- gsub("[^[:alnum:]_]", "_", cell_type)
    
    # foglio per cell_type con sottosezioni
    addWorksheet(wb, paste0(clean_name, "_all"))
    writeData(wb, paste0(clean_name, "_all"), res, rowNames = TRUE)
    
    addWorksheet(wb, paste0(clean_name, "_sig"))
    writeData(wb, paste0(clean_name, "_sig"), sig, rowNames = TRUE)
    
    addWorksheet(wb, paste0(clean_name, "_up"))
    writeData(wb, paste0(clean_name, "_up"), sig_up, rowNames = TRUE)
    
    addWorksheet(wb, paste0(clean_name, "_down"))
    writeData(wb, paste0(clean_name, "_down"), sig_down, rowNames = TRUE)
  }
  
  # salva il file excel del contrasto
  clean_contrast <- gsub("[^[:alnum:]_]", "_", contrast_name)
  saveWorkbook(wb, file = paste0(res_path,"dge_results/", clean_contrast, ".xlsx"), overwrite = TRUE)
}

```

